name: luka - Build and Publish ESPHome firmware

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

concurrency:
  group: esphome-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/esphome-build.yml
    with:
      files: >
        everything-presence-lite-ha.yaml,
        everything-presence-lite-ha-no-ble.yaml,
        everything-presence-lite-ha-ld2410.yaml,
        everything-presence-lite-ha-ld2410-no-ble.yaml,
        everything-presence-lite-ha-sen0395.yaml,
        everything-presence-lite-ha-sen0395-no-ble.yaml,
        everything-presence-lite-ha-sen0609.yaml,
        everything-presence-lite-ha-sen0609-no-ble.yaml,
        everything-presence-lite-ha-mr24hpc1.yaml,
        everything-presence-lite-ha-mr24hpc1-no-ble.yaml,
        everything-presence-lite-ha-co2.yaml,
        everything-presence-lite-ha-no-ble-co2.yaml,
        everything-presence-lite-ha-ld2410-co2.yaml,
        everything-presence-lite-ha-ld2410-no-ble-co2.yaml,
        everything-presence-lite-ha-sen0395-co2.yaml,
        everything-presence-lite-ha-sen0395-no-ble-co2.yaml,
        everything-presence-lite-ha-sen0609-co2.yaml,
        everything-presence-lite-ha-sen0609-no-ble-co2.yaml,
        everything-presence-lite-ha-mr24hpc1-co2.yaml,
        everything-presence-lite-ha-mr24hpc1-no-ble-co2.yaml
      name: Everything Presence Lite
      manifest_filename: manifest.json
      esphome_version: latest
